name: Sonar
description: Executes SonarCloud Analysis

inputs:
  project_name:
    description: project name
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup ${{ env.PROJECT_NAME }}
      uses: ./.github/actions/setup

    - name: Extract ${{ env.PROJECT_NAME }} package.json info
      id: projectinfo
      uses: gregoranders/nodejs-project-info@v0.0.20
      with:
        path: packages/${{ env.PROJECT_NAME }}/package.json

    - name: Generate ${{ env.PROJECT_NAME }} Unit Tests Coverage
      shell: bash
      run: pnpm exec nx run ${{ env.PROJECT_NAME }}:test --code-coverage --coverageReporters lcov --coverageDirectory packages/${{ env.PROJECT_NAME }} --skip-nx-cache

    - name: Modify ${{ env.PROJECT_NAME }} lcov.info
      shell: bash
      run: sed -i 's#packages/${{ env.PROJECT_NAME }}/##g' packages/${{ env.PROJECT_NAME }}/lcov.info

    - name: Generate ${{ env.PROJECT_NAME }} Lint Report
      shell: bash
      run: pnpm exec nx run ${{ env.PROJECT_NAME }}:lint --format json --outputFile packages/${{ env.PROJECT_NAME }}/eslint.json --skip-nx-cache

    - name: Modify ${{ env.PROJECT_NAME }} eslint.json
      shell: bash
      run: sed -i 's#/home/runner/work/aft-mf/aft-mf#/github/workspace#g' packages/${{ env.PROJECT_NAME }}/eslint.json

    - name: Analyze ${{ env.PROJECT_NAME }} in SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: packages/${{ env.PROJECT_NAME }}
        args: >
          -Dsonar.projectVersion=${{ steps.projectinfo.outputs.version }}
      # env:
      #   GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      #   SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
