name: Deploy Package
description: Deploy project package

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: ./.github/actions/setup

    - name: Build
      shell: bash
      run: pnpm exec nx run ${{ env.PROJECT_NAME }}:build

    - name: Deploy in npm.js
      shell: bash
      run: pnpm publish dist/packages/${{ env.PROJECT_NAME }} --access=public
