name: Deploy Package
description: Deploy project package

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup ${{ env.PROJECT_NAME }}
      uses: ./.github/actions/setup

    - name: Build ${{ env.PROJECT_NAME }}
      shell: bash
      run: pnpm exec nx run ${{ env.PROJECT_NAME }}:build --skip-nx-cache

    - name: Deploy ${{ env.PROJECT_NAME }} in npm.js
      shell: bash
      run: pnpm publish dist/packages/${{ env.PROJECT_NAME }} --access=public
