name: Deploy Package
description: Deploy project package

inputs:
  project_name:
    description: project name
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup ${{ github.event.inputs.project_name }}
      uses: ./.github/actions/setup

    - name: Build ${{ github.event.inputs.project_name }}
      shell: bash
      run: pnpm exec nx run ${{ github.event.inputs.project_name }}:build --skip-nx-cache

    - name: Deploy ${{ github.event.inputs.project_name }} in npm.js
      shell: bash
      run: pnpm publish dist/packages/${{ github.event.inputs.project_name }} --access=public
