name: Deploy Package
description: Deploy project package

inputs:
  project_name:
    description: project name
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: ./.github/actions/setup

    - name: Build
      shell: bash
      run: pnpm exec nx run ${{ input.project_name }}:build --skip-nx-cache

    - name: Deploy in npm.js
      shell: bash
      run: pnpm publish dist/packages/${{ input.project_name }} --access=public
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
