name: Deploy Documentation
description: Deploy project Documentation

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Setup ${{ env.PROJECT_NAME }}
      uses: ./.github/actions/setup

    - name: Generate ${{ env.PROJECT_NAME }} documentation
      shell: bash
      run: pnpm exec nx run ${{ env.PROJECT_NAME }}:docs --no-cloud

    - name: Deploy ${{ env.PROJECT_NAME }} documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        publish_dir: docs/packages/${{ env.PROJECT_NAME }}
        destination_dir: ${{ env.PROJECT_NAME }}
