name: AFT-MF CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/*/src/**

concurrency:
  group: ci-aft-mf-${{ github.ref }}-1
  cancel-in-progress: true

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 20, 22]
    name: Test Affected on NodeJS ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

      - name: Test Affected
        run: pnpm exec nx affected --target=test --no-cloud

  build-lint:
    runs-on: ubuntu-latest
    name: Build & Lint Affected
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint Affected
        run: pnpm exec nx affected --target=lint --no-cloud

      - name: Build Affected
        run: pnpm exec nx affected --target=build --no-cloud

  version:
    needs: [test, build-lint]
    runs-on: ubuntu-latest
    name: Generate Affected Versions
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Version Affected
        run: pnpm exec nx affected --target=version --parallel=1 --no-cloud
