name: AFT-MF Common CD

on:
  push:
    tags:
      - 'common-v*'
  workflow_dispatch:

concurrency:
  group: ci-common-${{ github.ref }}-1
  cancel-in-progress: true

env:
  HUSKY: 0
  GITHUB_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    name: Generate Reports and Analyze in SonarCloud
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sonar
        with:
          project-name: common

  deploy_package:
    needs: sonarcloud
    runs-on: ubuntu-latest
    name: Generate and Deploy Package
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-package
        with:
          project-name: common

  deploy_docs:
    needs: sonarcloud
    runs-on: ubuntu-latest
    name: Generate and Deploy Documentation
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-docs
        with:
          project-name: common
